### ISSUE TITLE
Violating the license of my code

### ISSUE THREAD

**Issue by pelrun** [honjow/GPD-WinControl#10]
I released pelrun/pyWinControls under the GPL license. The license does *not allow* you to copy it into a BSD-licensed codebase and republish it.

Geez, you couldn't even ask first?

**Comment by honjow** [comment]
Sorry I didn't notice the license , I will clean up this project

**Comment by pelrun** [comment]
I appreciate the gesture, but it's a bit extreme! I just wanted to have the conversation - strictly speaking I'm not welded to the GPL and should probably just relicense it to BSD myself.

**Comment by honjow** [comment]
After all, it was my fault first. But if you consider allowing me to use your code, I will try to republish.

**Comment by pelrun** [comment]
Yeah, you can use it under the BSD license as of now; I'll update the official license on my repo when I get the chance.
