### ISSUE TITLE
Unable to configure the R4 and L4 buttons

### ISSUE THREAD

**Issue by eidleweise** [honjow/GPD-WinControl#6]
The R4 and L4 buttons on 1st launch appear as such

![20240429_190209](https://github.com/honjow/GPD-WinControl/assets/61235522/c1d4a259-cff6-463b-962c-875789155597)

1. Setting any of the combo boxes to anything is resulting in the value appearing briefly and then dissapearing again as well as apparently not being set.
2. Deleting from the top didn't appear to do anything.
3. Deleting from the bottom allows me to remove extraneous selection boxes all the way to having non and an "add" button appearing.
4. Pressing the add button brings up the combo box, but once again selecting a value briefly results in the value being seen, and 4 extra selection boxes appearing.

I've also verified by going into windows that the default buttons are:
<img width="714" alt="winctrl" src="https://github.com/honjow/GPD-WinControl/assets/61235522/610956b1-78e6-465e-8bfc-b41d8a81af02">

**Comment by honjow** [comment]
First, update to version 1.1.6, I have added some log outputs.
Then check the contents of `/tmp/GPD-WinControl.log`.

**Comment by eidleweise** [comment]
[GPD-WinControl.log](https://github.com/honjow/GPD-WinControl/files/15198427/GPD-WinControl.log)
One log file coming up

**Comment by honjow** [comment]
try [1.1.7](https://github.com/honjow/GPD-WinControl/releases/tag/v1.1.7)

**Comment by honjow** [comment]
Try version 1.1.7

**Comment by eidleweise** [comment]
That got it! 
![Screenshot_20240503-131149](https://github.com/honjow/GPD-WinControl/assets/61235522/5622c5f0-02d0-4246-9ccc-65acdaee4c9e)
